CREATE DATABASE quanlykho_moi;
USE quanlykho_moi;

-- 1. KHO
CREATE TABLE KHO (
    MaKho VARCHAR(10) PRIMARY KEY,
    TenKho VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(200)
);

-- 2. NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(200),
    SDT VARCHAR(15)
);

-- 3. KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(200),
    SDT VARCHAR(15)
);

-- 4. NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(100) NOT NULL,
    ChucVu VARCHAR(50),
    SDT VARCHAR(15),
    Email VARCHAR(100)
);

-- 5. NGUOIGIAOHANG
CREATE TABLE NGUOIGIAOHANG (
    MaGH VARCHAR(10) PRIMARY KEY,
    TenGH VARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    PhuongTien VARCHAR(50)
);

-- 6. HANGHOA
CREATE TABLE HANGHOA (
    MaHH VARCHAR(10) PRIMARY KEY,
    TenHH VARCHAR(100) NOT NULL,
    Loai VARCHAR(50),
    DonVi VARCHAR(20),
    GiaNhap DECIMAL(15,2) DEFAULT 0,
    GiaBan DECIMAL(15,2) DEFAULT 0,
    SoLuongTon INT DEFAULT 0
);

-- 7. PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE NOT NULL,
    MaNCC VARCHAR(10),
    MaNV VARCHAR(10),
    MaKho VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaKho) REFERENCES KHO(MaKho)
);

-- 8. CHITIETPHIEUNHAP
CREATE TABLE CHITIETPHIEUNHAP (
    MaPN VARCHAR(10),
    MaHH VARCHAR(10),
    SoLuong INT DEFAULT 0,
    DonGia DECIMAL(15,2) DEFAULT 0,
    PRIMARY KEY (MaPN, MaHH),
    FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN) ON DELETE CASCADE,
    FOREIGN KEY (MaHH) REFERENCES HANGHOA(MaHH) ON DELETE CASCADE
);

-- 9. PHIEUXUAT
CREATE TABLE PHIEUXUAT (
    MaPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE NOT NULL,
    MaKH VARCHAR(10),
    MaNV VARCHAR(10),
    MaKho VARCHAR(10),
    MaGH VARCHAR(10),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),
    FOREIGN KEY (MaGH) REFERENCES NGUOIGIAOHANG(MaGH)
);

-- 10. CHITIETPHIEUXUAT
CREATE TABLE CHITIETPHIEUXUAT (
    MaPX VARCHAR(10),
    MaHH VARCHAR(10),
    SoLuong INT DEFAULT 0,
    DonGia DECIMAL(15,2) DEFAULT 0,
    PRIMARY KEY (MaPX, MaHH),
    FOREIGN KEY (MaPX) REFERENCES PHIEUXUAT(MaPX) ON DELETE CASCADE,
    FOREIGN KEY (MaHH) REFERENCES HANGHOA(MaHH) ON DELETE CASCADE
);
